7,8칸 같이 길이가 긴 경우 수정
karpitony/dodle pull request #3
Opened 2024-09-14 15:37 UTC by karpitony

# 바로 머지 박지말고 11시 55분쯤에 박기!!
# 정답 바뀐다!!!

2024-09-14 15:39 UTC, karpitony commented
모바일에서 입력 버튼이 사리지는 이슈 발견

2024-09-14 15:55 UTC, karpitony commented
# [미리보기 데모](https://dodle-git-fix-if-lenght-is-8-yuyuyunseoks-projects.vercel.app/)
# [남양주 버전](https://dodle-git-test-long-dosiname-yuyuyunseoks-projects.vercel.app/)

2024-09-14 16:06 UTC, 5tarlight requested changes

2024-09-14 16:06 UTC, 5tarlight commented on src/components/game/Cell.jsx
> +    } else if (jamoLength === 8) {
8보다 클 경우에도 생각.
8보다 큰 경우가 없어도 일반적으로 혹시모를 오류를 방지하기위해 `>=` 로 쓰는편

2024-09-14 16:13 UTC, karpitony commented on src/components/game/Cell.jsx
> +    } else if (jamoLength === 8) {
내일 아침에 반영하겠습니다. 좋은꿈 꾸세용 ~ ;)

2024-09-14 16:14 UTC, 5tarlight commented on src/components/game/Cell.jsx
> +    } else if (jamoLength === 8) {
🛌

2024-09-15 02:58 UTC, 5tarlight approved these changes

2024-09-15 12:56 UTC, karpitony commented
- `구` 데이터 추가 및 데이터 최신으로 업데이트(#4 )
- 글자 크기에 따른 모바일에서 셀 크기 조절

2024-09-15 12:56 UTC, merged